# Global 全局配置
hoster: <a href="https://github.io" target="_blank">Github Pages</a>
site_logo: images/myico.ico
snow: false
click_animate_js: 'candy'
enable_dark: true
highlight_theme: night-eighties # 代码高亮主题（light | night | night-eighties | night-blue | night-bright）
cdn: false
check_update: false
# canonical: true

# 自定义样式
customStyles:
  images: # 图片相关设置
    # banner: /images/banner.webp # 站点横幅
    # background: /images/bg.jpeg # 站点背景

# Index 首页配置
index:
  post_type: false
  read_count: true
  comment_count: false

# Top Menu 顶部导航栏配置 （具体格式请参照文档）
menu:
  index: /
  archives: /archives/
  # friends: /friends/
  # sites:
  #   submenu: true
  #   author: https://candinya.com
  #   project: https://github.com/Candinya/Kratos-Rebirth

label:
  index: <i class="fa fa-home"></i>首页
  archives: <i class="fa fa-file"></i>归档
  # friends: <i class="fa fa-paw"></i>好伙伴
  # sites:
  #   submenu: <i class="fa fa-link"></i>链接
  #   author: 作者博客
  #   project: 项目链接

# Footer 页脚配置
group_link: 
contact: # 出于兼容性考虑，继续保留
  weibo: 
  mail: cyqun@qq.com
  github: qun-qq
  rss:
footerLinks: [] # 可以自定义
timenotice: 本站已运行
icp: 
psr:
  
# Post Page 文章页配置
posts:
  show_cc: true
  share: true
  wordCount: 
    enable: true
    threshold: 1500


# Widgets 侧边栏小挂件
sidebar: left
widgets:
- about
- splitter
- category
- tagcloud
- posts
avatarUri: /images/cyq.webp
mobile_toc: 
  hide: false
  hide_id: false

# Fancybox 文章内图片单击放大
fancybox: true

# Search 搜索
search:
  enable: true
  path: search.json
  field: post # page | post | all. Default post
  content: true # Include post | page content

# JavaScript 相关配置
## 由于Javascript被压缩后难以有效编辑与生成，因而为了简化操作，将相关的配置项在生成文件时以独立的json文件写出，调用时使用fetch API获取。
jsconfig:
  main:
    cover:
      randomAmount: 20 # 表示从1~20
      filenameTemplate: "thumb_{no}.webp" 
    createTime: "2023/07/29 17:28:12"
    donateBtn: "支持我~"
    scanNotice: "扫一扫"
    qr_alipay: "/images/alipayqr.webp"
    qr_wechat: "/images/wechatpayqr.webp"
    siteLeaveEvent: false
    leaveTitle: "{{{(>_<)}}}崩溃了~"
    returnTitle: "(*´∇ *)又好了~"
    copyrightNotice: "该内容采用 CC BY-NC-SA 4.0 许可协议，著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"
    expire_day: 30
    topNavScrollToggle: true


# Friends 友链相关内容
friends:
  href: "friends"
  page:
    title: "友情链接"
    comments: false
    description: "友情链接~"
    updated: "2021-01-18"
  verify: true # 验证每个友链的可访问性，炸了会有提示

# Misc 杂项
misc:
  showWordCountEstimateWavy: true # 在文章字数处显示表示大约字数的波浪号
